pipeline {
    agent any
    tools {
        maven "Maven_3.9.6"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                checkout scm

                // Run Maven on a Unix agent.
                sh "mvn -Dmaven.test.failure.ignore=true clean package"

                // To run Maven on a Windows agent, use
                // bat "mvn -Dmaven.test.failure.ignore=true clean package"
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage('BUILD') {
            steps {
                checkout scm
                sh "mvn -Dmaven.test.failure.ignore=true -s settings.xml clean deploy"
            }
            post {
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        // stage('SonarQube Analysis') {
        //     steps {
        //       withSonarQubeEnv('sonar') {
        //           sh "mvn clean verify sonar:sonar -Dsonar.projectKey=myapp"
        //       }
        //     }
        // }
    }
}